<a href="https://colab.research.google.com/github/Zamoca42/TIL/blob/main/AIME220914.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

list_num = [1,2,3,4]

nparr = np.array(list_num)

print(list_num)
print(nparr)

<class 'list'>
[1, 2, 3, 4]
[1 2 3 4]


In [8]:
print("np.zeros(5) ₩n", np.zeros(5))
print("np.zeros((2,3)) ₩n", np.zeros((2,3)))

np.zeros(5) ₩n [0. 0. 0. 0. 0.]
np.zeros((2,3)) ₩n [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print("np.ones(5) ₩n", np.ones(5))
print("np.ones((2,3)) ₩n", np.ones((2,3)))

np.ones(5) ₩n [1. 1. 1. 1. 1.]
np.ones((2,3)) ₩n [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print("np.arange(10) ₩n", np.arange(10))
print("np.arange(2,5) ₩n", np.arange(2,5))

np.arange(10) ₩n [0 1 2 3 4 5 6 7 8 9]
np.arange(2,5) ₩n [2 3 4]


In [16]:
print(nparr[1])
print(nparr[1:2])

2
[2]


In [17]:
arr1 = np.arange(5)
print("arr1 : ", arr1)
print("arr1[0] : ", arr1[0])
print("arr1[3] : ", arr1[3])
print("arr1[2:4] : ", arr1[2:4])
print("arr1[:] : ", arr1[:])

arr1 :  [0 1 2 3 4]
arr1[0] :  0
arr1[3] :  3
arr1[2:4] :  [2 3]
arr1[:] :  [0 1 2 3 4]


In [20]:
print(nparr[1])
print(nparr[1:2])
# 독립적이지만 다음에 실행하는 결과에 영향을 미친다

['10' '11' '12' '13']
[['10' '11' '12' '13']]


In [24]:
nparr = np.array([['00','01','02','03'],['10','11','12','13'],['20','21','22','23']])

print(nparr)
print(nparr[1,2])
print(nparr[1,:])
print(nparr[0:2,1])
print(nparr[0+2,1])
print(nparr[[0,2],1]) # 특정 값 뽑아내기
print(nparr[[0,2],:])

[['00' '01' '02' '03']
 ['10' '11' '12' '13']
 ['20' '21' '22' '23']]
12
['10' '11' '12' '13']
['01' '11']
21
['01' '21']
[['00' '01' '02' '03']
 ['20' '21' '22' '23']]


In [25]:
print("0~1 사이 랜덤 값 \n", np.random.rand(2,4))
print("정규분포 랜덤 값 (기대값 0, 표준편차 1) \n", np.random.randn(2,4))
print("절대값 \n", np.abs([1, -2, -3, 2]))
print("제곱근 \n", np.sqrt([1, 2, 3, 4]))
print("제곱 \n", np.square([1, 2, 3, 4]))

0~1 사이 랜덤 값 
 [[0.75084451 0.64242931 0.54725321 0.27734823]
 [0.95431552 0.56212039 0.629066   0.68656139]]
정규분포 랜덤 값 (기대값 0, 표준편차 1) 
 [[-2.17208499 -1.39549147 -1.02592132  1.5711715 ]
 [ 0.20595471 -0.32782496 -2.04914199  0.5301672 ]]
절대값 
 [1 2 3 2]
제곱근 
 [1.         1.41421356 1.73205081 2.        ]
제곱 
 [ 1  4  9 16]


In [28]:
arr1 = np.array([[1,2,3,4],[8,8,6,5]])
print(arr1)
print(np.sum(arr1, axis=1))
print(arr1.sum(axis=1))
print(np.sum(arr1, axis=0))
print(arr1.sum(axis=0))
# average
print(arr1.mean(axis=0)) 
print(arr1.mean(axis=1)) # axis = 차원
# std = 표준편차
print(arr1.std(axis=0)) 
print(arr1.std(axis=1))
# 최솟값
print(arr1.min(axis=0))
print(arr1.min(axis=1))
# 최소값의 좌표
print(arr1.argmin(axis=0))
print(arr1.argmin(axis=1))

[[1 2 3 4]
 [8 8 6 5]]
[10 27]
[10 27]
[ 9 10  9  9]
[ 9 10  9  9]
[4.5 5.  4.5 4.5]
[2.5  6.75]
[3.5 3.  1.5 0.5]
[1.11803399 1.29903811]
[1 2 3 4]
[1 5]
[0 0 0 0]
[0 3]


In [38]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
arr2 = arr1.reshape(3,2)
print(arr2)
arr3 = arr1.reshape(-1,2,3) # -1 은 '알아서 계산하라'는 뜻
print(arr3)
arr4 = arr1.reshape(6,1)
print(arr4)
arr5 = arr4.squeeze() # shape에서 1인 파트를 제거
arr2 = arr2.squeeze()
print(arr5)
print(arr2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]
  [4 5 6]]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [40]:
import pandas as pd

data = {'name' : ['Kim', 'Lee', 'Park'],
        'score1' : [100,90,70],
        'score2' : [80,70,90], 
        }
df = pd.DataFrame(data)
print(df)
print(type(df))

   name  score1  score2
0   Kim     100      80
1   Lee      90      70
2  Park      70      90
<class 'pandas.core.frame.DataFrame'>


In [44]:
df1 = pd.DataFrame(df,columns = ['score1','name','score2'])
print(df1)

   score1  name  score2
0     100   Kim      80
1      90   Lee      70
2      70  Park      90


In [47]:
df2 = pd.DataFrame(data,columns = ['name','score1','score2'], index=['a','b','c'])
print(df2)

   name  score1  score2
a   Kim     100      80
b   Lee      90      70
c  Park      70      90


In [51]:
print(df2.name)
dfname=df2.name
print(dfname)
print(type(dfname))
dfname = df2['name']
dfname=df2[df2.columns[0]]
dfname=df2.iloc[:,0] # index로 읽는 로케이션
dfname=df2.loc[:,'name'] # key로 읽는 로케이션
dfname=df2.loc[:,df2.columns[0]]
print(dfname)
print(df2.columns[0])

a     Kim
b     Lee
c    Park
Name: name, dtype: object
a     Kim
b     Lee
c    Park
Name: name, dtype: object
<class 'pandas.core.series.Series'>
a     Kim
b     Lee
c    Park
Name: name, dtype: object
name
