<a href="https://colab.research.google.com/github/Zamoca42/TIL/blob/main/AIME220914.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# 2022. 09. 14 (수) 
import numpy as np

list_num = [1,2,3,4]

nparr = np.array(list_num)

print(list_num)
print(nparr)

[1, 2, 3, 4]
[1 2 3 4]


In [6]:
print("np.zeros(5) ₩n", np.zeros(5))
print("np.zeros((2,3)) ₩n", np.zeros((2,3)))

np.zeros(5) ₩n [0. 0. 0. 0. 0.]
np.zeros((2,3)) ₩n [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print("np.ones(5) ₩n", np.ones(5))
print("np.ones((2,3)) ₩n", np.ones((2,3)))

np.ones(5) ₩n [1. 1. 1. 1. 1.]
np.ones((2,3)) ₩n [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print("np.arange(10) ₩n", np.arange(10))
print("np.arange(2,5) ₩n", np.arange(2,5))

np.arange(10) ₩n [0 1 2 3 4 5 6 7 8 9]
np.arange(2,5) ₩n [2 3 4]


In [9]:
print(nparr[1])
print(nparr[1:2])

2
[2]


In [10]:
arr1 = np.arange(5)
print("arr1 : ", arr1)
print("arr1[0] : ", arr1[0])
print("arr1[3] : ", arr1[3])
print("arr1[2:4] : ", arr1[2:4])
print("arr1[:] : ", arr1[:])

arr1 :  [0 1 2 3 4]
arr1[0] :  0
arr1[3] :  3
arr1[2:4] :  [2 3]
arr1[:] :  [0 1 2 3 4]


In [11]:
print(nparr[1])
print(nparr[1:2])
# 독립적이지만 다음에 실행하는 결과에 영향을 미친다

2
[2]


In [12]:
nparr = np.array([['00','01','02','03'],['10','11','12','13'],['20','21','22','23']])

print(nparr)
print(nparr[1,2])
print(nparr[1,:])
print(nparr[0:2,1])
print(nparr[0+2,1])
print(nparr[[0,2],1]) # 특정 값 뽑아내기
print(nparr[[0,2],:])

[['00' '01' '02' '03']
 ['10' '11' '12' '13']
 ['20' '21' '22' '23']]
12
['10' '11' '12' '13']
['01' '11']
21
['01' '21']
[['00' '01' '02' '03']
 ['20' '21' '22' '23']]


In [13]:
print("0~1 사이 랜덤 값 \n", np.random.rand(2,4))
print("정규분포 랜덤 값 (기대값 0, 표준편차 1) \n", np.random.randn(2,4))
print("절대값 \n", np.abs([1, -2, -3, 2]))
print("제곱근 \n", np.sqrt([1, 2, 3, 4]))
print("제곱 \n", np.square([1, 2, 3, 4]))

0~1 사이 랜덤 값 
 [[0.73550678 0.86614161 0.25447687 0.54183642]
 [0.91242418 0.72423274 0.98709179 0.2259472 ]]
정규분포 랜덤 값 (기대값 0, 표준편차 1) 
 [[-0.78213414  0.75104934  0.29779566 -1.42899947]
 [-0.51448821  0.8330605  -0.0552216   0.1160866 ]]
절대값 
 [1 2 3 2]
제곱근 
 [1.         1.41421356 1.73205081 2.        ]
제곱 
 [ 1  4  9 16]


In [14]:
arr1 = np.array([[1,2,3,4],[8,8,6,5]])
print(arr1)
print(np.sum(arr1, axis=1))
print(arr1.sum(axis=1))
print(np.sum(arr1, axis=0))
print(arr1.sum(axis=0))
# average
print(arr1.mean(axis=0)) 
print(arr1.mean(axis=1)) # axis = 차원
# std = 표준편차
print(arr1.std(axis=0)) 
print(arr1.std(axis=1))
# 최솟값
print(arr1.min(axis=0))
print(arr1.min(axis=1))
# 최소값의 좌표
print(arr1.argmin(axis=0))
print(arr1.argmin(axis=1))

[[1 2 3 4]
 [8 8 6 5]]
[10 27]
[10 27]
[ 9 10  9  9]
[ 9 10  9  9]
[4.5 5.  4.5 4.5]
[2.5  6.75]
[3.5 3.  1.5 0.5]
[1.11803399 1.29903811]
[1 2 3 4]
[1 5]
[0 0 0 0]
[0 3]


In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
arr2 = arr1.reshape(3,2)
print(arr2)
arr3 = arr1.reshape(-1,2,3) # -1 은 '알아서 계산하라'는 뜻
print(arr3)
arr4 = arr1.reshape(6,1)
print(arr4)
arr5 = arr4.squeeze() # shape에서 1인 파트를 제거
arr2 = arr2.squeeze()
print(arr5)
print(arr2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]
  [4 5 6]]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [40]:
import pandas as pd

data = {'name' : ['Kim', 'Lee', 'Park'],
        'score1' : [100,90,70],
        'score2' : [80,70,90], 
        }
df = pd.DataFrame(data)
print(df)
print(type(df))

   name  score1  score2
0   Kim     100      80
1   Lee      90      70
2  Park      70      90
<class 'pandas.core.frame.DataFrame'>


In [41]:
df1 = pd.DataFrame(df,columns = ['score1','name','score2'])
print(df1)

   score1  name  score2
0     100   Kim      80
1      90   Lee      70
2      70  Park      90


In [42]:
df2 = pd.DataFrame(data,columns = ['name','score1','score2'], index=['a','b','c'])
print(df2)

   name  score1  score2
a   Kim     100      80
b   Lee      90      70
c  Park      70      90


In [45]:
#print(df2.name)
#dfname=df2.name
#print(dfname)
#print(type(dfname))
dfname = df2['name']
dfname=df2[df2.columns[0]]
dfname=df2.iloc[:,0] # index로 접근하는 로케이션
#dfname=df2.iloc[:,[0,2]]
#dfname=df2.loc[:,'name'] # key로 접근하는 로케이션
#dfname=df2.loc[:,['name','score2']]
#dfname=df2.loc[:,df2.columns[0]]
print(dfname)
print(df2.columns[0])

a     Kim
b     Lee
c    Park
Name: name, dtype: object
name


In [22]:
# 2022. 09. 19(월)

## df_temp = df2.iloc[1,0]
## df_temp = df2.loc['b', 'name']
## df_temp = df2.loc[df2.index[1], df2.columns[0]]

# 데이터를 여러개 추출

## df_temp = df2.loc[['a','b'], 'name']
## df_temp = df2.iloc[[0:2,4],[0,2]] 

# print(df_temp)

In [23]:
df2['score3'] = [20,30,50]

print(df2)

   name  score1  score2  score3
a   Kim     100      80      20
b   Lee      90      70      30
c  Park      70      90      50


In [24]:
data = pd.Series([60,70],index=['b','c'])
df2['score4'] = data

print(df2) 

# missing data = NaN
# NaN이 들어가는 data는 예외처리 필요

   name  score1  score2  score3  score4
a   Kim     100      80      20     NaN
b   Lee      90      70      30    60.0
c  Park      70      90      50    70.0


In [25]:
# data1 = ['one','two', 3]
data1 = [1, 2, 3, 4, 5, 6]

for i in data1:
  print(i)

1
2
3
4
5
6


In [26]:
for i in range(3):
  print(data1[i])

1
2
3


In [27]:
data1 = [[1,2],[3,4],[5,6]]

for i in data1:
  print('i :', i)
  print(i[0])
  print(i[1])

i : [1, 2]
1
2
i : [3, 4]
3
4
i : [5, 6]
5
6


In [28]:
data1 = [[1,2,3],[3,4,5],[5,6,7]]

for i,j,k in data1:
  print(i)
  print(j)
  print(k)

1
2
3
3
4
5
5
6
7


In [29]:
for i in range(1,11):
  if (i%2 == 0):
    print(i, "= 짝수")
  elif(i%3 == 0):
    print(i, "= 3의 배수")
  else:
    print(i, "= 짝수도 3의 배수도 아님")

1 = 짝수도 3의 배수도 아님
2 = 짝수
3 = 3의 배수
4 = 짝수
5 = 짝수도 3의 배수도 아님
6 = 짝수
7 = 짝수도 3의 배수도 아님
8 = 짝수
9 = 3의 배수
10 = 짝수


In [30]:
i = 1

while i <= 11 : 
  if (i%2 == 0):
    print(i, "= 짝수")
  elif(i%3 == 0):
    print(i, "= 3의 배수")
  else:
    print(i, "= 짝수도 3의 배수도 아님")
  i=i+1


1 = 짝수도 3의 배수도 아님
2 = 짝수
3 = 3의 배수
4 = 짝수
5 = 짝수도 3의 배수도 아님
6 = 짝수
7 = 짝수도 3의 배수도 아님
8 = 짝수
9 = 3의 배수
10 = 짝수
11 = 짝수도 3의 배수도 아님


In [31]:
def add_sub(a,b):
  return a+b, a-b

a=4
b=2

# c,d = add_sub(a,b)
_,d = add_sub(a,b)
c,_ = add_sub(a,b)
# print(d)
print(c)

6


In [32]:
# 2022. 09. 21

## test.txt 파일 생성 후 업로드

# /content/drive/MyDrive/Colab Notebooks/test.txt

from google.colab import files
# uploaded = files.upload()

In [33]:
f = open("/content/drive/MyDrive/Colab Notebooks/test.txt", 'r')
# line = f.readline()
while True : 
  line = f.readline()
  if not line: break
  print(line)
f.close()

hello hi

good morning



111

22

3

4

5

666


In [36]:
f = open("/content/drive/MyDrive/Colab Notebooks/test.txt", 'r')

lines = f.readlines()

print(lines)

for i in lines:
  print(i)

for i in range(len(lines)) :
  print(lines[i])

f.close()

['hello hi\n', 'good morning\n', '\n', '111\n', '22\n', '3\n', '4\n', '5\n', '666']
hello hi

good morning



111

22

3

4

5

666
hello hi

good morning



111

22

3

4

5

666


In [43]:
f = open("/content/test1.txt", 'w')
f.write("hello \n")
f.write("test \n")
f.write("32541637 \n")

a = 100.1
f.write(str(a)+'\n')
str_data = "이렇게도 쓸 수 있습니다 \n%.2f\n" %a

f.write(str_data)
f.close()

In [50]:
import pandas as pd

data1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/csvtest.csv", encoding="utf-8", sep=',', index_col=[0], header=[0])
print(data1)

   Name  Math  Science  history  music  Unnamed: 6
a   100    90       70      100     90         NaN
b    90    80      100      100     80         NaN
c    80    89       80      100     70         NaN
d    70    90       70      100     60         NaN
e    60   100       50      100     50         NaN
f    50   100       60      100     40         NaN


In [53]:
data_temp = pd.Series([60,70,90], index=['b','c','f'])
data1['art'] = data_temp

print(data1)

   Name  Math  Science  history  music  Unnamed: 6   art
a   100    90       70      100     90         NaN   NaN
b    90    80      100      100     80         NaN  60.0
c    80    89       80      100     70         NaN  70.0
d    70    90       70      100     60         NaN   NaN
e    60   100       50      100     50         NaN   NaN
f    50   100       60      100     40         NaN  90.0


In [55]:
data1.to_csv("/content/drive/MyDrive/Colab Notebooks/csv_result.csv",mode='w')

In [61]:
# data1 = data1.drop(['Unnamed: 6'],axis='columns')
# 열 삭제해보기

print(data1)

   Name  Math  Science  history  music   art
a   100    90       70      100     90   NaN
b    90    80      100      100     80  60.0
c    80    89       80      100     70  70.0
d    70    90       70      100     60   NaN
e    60   100       50      100     50   NaN
f    50   100       60      100     40  90.0


In [61]:
# HomeWork

import pandas as pd

data2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Hwtest.csv", encoding="utf-8", sep=',', index_col=[0], header=[0])

data10 = pd.DataFrame({'i*10': range(data2.shape[0])})

for i in range(data2.shape[0]):
   data10.iloc[i,0] = i * 10

data2['Unnamed: 1'] = data10
data2.rename(columns = {'Unnamed: 1':'i*10'}, inplace = True)

print(data2)
# data2.to_csv(~)


    i*10
I       
0      0
1     10
2     20
3     30
4     40
5     50
6     60
7     70
8     80
9     90
10   100
