<a href="https://colab.research.google.com/github/Zamoca42/TIL/blob/main/AI/keras_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

def onehot_to_class(prediction):
  idx = prediction.argmax(axis = 0)

  if idx == 0:
    return str(0)
  if idx == 1:
    return str(1)
  if idx == 2:
    return str(2)
  else :
    return 'error'



# input
X_train = [[0,0],[0,1],[1,0],[1,1]]
X_train = np.array(X_train)

# output
Y_train=[[0],[1],[1],[2]] # 숫자로 분류할 때
# Y_train=[[1,0,0],[0,1,0],[0,1,0],[0,0,1]]

Y_train = (tensorflow.keras.utils.to_categorical(Y_train))

print(Y_train)

model = keras.models.Sequential([
    keras.layers.Dense(units=4, activation='relu', input_shape=[2]),
    keras.layers.Dense(units=2, activation='sigmoid'), 
    keras.layers.Dense(units=3, activation='softmax'), # 출력이 여러가지
])

# units = 해당 layer의 Neuron의 갯수

opt = keras.optimizers.Adam(learning_rate=0.1)

# model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=['accuracy']) # 숫자로 분류할 때
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy']) # one-hot encoding

hist = model.fit(X_train, Y_train, batch_size=4, epochs=100, shuffle=True, verbose = 0)

print(model.weights)
print("0,0 -> ", onehot_to_class(model.predict([[0,0]])[0]))
print("0,1 -> ", onehot_to_class(model.predict([[0,1]])[0]))
print("1,0 -> ",onehot_to_class(model.predict([[1,0]])[0]))
print("1,1 -> ", onehot_to_class(model.predict([[1,1]])[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[<tf.Variable 'dense_9/kernel:0' shape=(2, 4) dtype=float32, numpy=
array([[ 2.4334505 ,  2.821953  , -0.3167658 ,  2.3563223 ],
       [-2.4430728 ,  1.5909126 , -0.33014655,  2.6804435 ]],
      dtype=float32)>, <tf.Variable 'dense_9/bias:0' shape=(4,) dtype=float32, numpy=array([-0.03113105, -1.2180376 ,  0.        , -0.604933  ], dtype=float32)>, <tf.Variable 'dense_10/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 2.2533977 ,  2.8736522 ],
       [-2.1630995 ,  3.5727046 ],
       [-0.50213766,  0.50738454],
       [-0.6580256 ,  3.4105844 ]], dtype=float32)>, <tf.Variable 'dense_10/bias:0' shape=(2,) dtype=float32, numpy=array([ 4.9933333, -3.347811 ], dtype=float32)>, <tf.Variable 'dense_11/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[ 4.117405 ,  2.3446457, -6.8036594],
       [-5.7943754,  3.1819534,  4.1658   ]], dtype=float32)>, <tf.Variable 'dense_11/bias:0' shape=(3,) dtype=float32, numpy=array([ 0.91015154, -

In [ ]:
temp_list = np.array([0 , 10, 3, 5, 7])
print(temp_list.argmax(axis=0)) # max 값이 들어있는 index 출력
print(temp_list.argmin(axis=0)) # min 값이 들어있는 index 출력

1
0


In [ ]:
(X_train, Y_train), (X_test,Y_test) = keras.datasets.mnist.load_data()