<a href="https://colab.research.google.com/github/Zamoca42/TIL/blob/main/AI/keras_activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# tanh, ReLU, sigmoid
# https://www.v7labs.com/blog/neural-networks-activation-functions

from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

# and, or, xor gate

# input
X_train=[[0,0],[0,1],[1,0],[1,1]]

# output
# Y_train=[0,0,0,1] 'and' gate
# Y_train=[0,1,1,1] # 'or' gate
Y_train=[0,1,1,0] # 'xor' gate

model = keras.models.Sequential([
    keras.layers.Dense(units=2, activation='tanh', input_shape=[2]),# weight = input * units -> 2 * 2
    keras.layers.Dense(units=2, activation='tanh'),
    keras.layers.Dense(units=1, activation='sigmoid'), # 출력이 0또는 1
])

# units = Neuron의 갯수

opt = keras.optimizers.Adam(learning_rate=0.1)

model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

hist = model.fit(X_train,Y_train, batch_size=4, epochs=1000, shuffle = True, verbose = 0)

print(model.weights)
print("0 xor 0 -> ",model.predict([[0,0]]))
print("0 xor 1 -> ",model.predict([[0,1]]))
print("1 xor 0 -> ",model.predict([[1,0]]))
print("1 xor 1 -> ",model.predict([[1,1]]))

[<tf.Variable 'dense_3/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.6366147, -3.3632686],
       [ 1.6371591, -3.0237212]], dtype=float32)>, <tf.Variable 'dense_3/bias:0' shape=(2,) dtype=float32, numpy=array([-2.291348,  1.110479], dtype=float32)>, <tf.Variable 'dense_4/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-5.0400414 ,  0.97598547],
       [ 0.01751438, -3.7678556 ]], dtype=float32)>, <tf.Variable 'dense_4/bias:0' shape=(2,) dtype=float32, numpy=array([0.40559042, 0.41836688], dtype=float32)>, <tf.Variable 'dense_5/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[7.9297595],
       [8.19083  ]], dtype=float32)>, <tf.Variable 'dense_5/bias:0' shape=(1,) dtype=float32, numpy=array([-7.7626724], dtype=float32)>]
1/1 [==============================] - 0s 64ms/step
0 xor 0 ->  [[0.00033166]]
1/1 [==============================] - 0s 32ms/step
0 xor 1 ->  [[0.9997564]]
1/1 [==============================] - 0s 30ms/step
1 xor 0 ->  [[0.99975693]]
1/1 [========

In [3]:
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

# input
X_train=[[0,0],[0,1],[1,0],[1,1]]

# output
# Y_train=[0,0,0,1] 'and' gate
# Y_train=[0,1,1,1] # 'or' gate
# Y_train=[0,1,1,0] # 'xor' gate

# 2-output
Y_train=[[0,0],[1,0],[1,0],[0,1]]
# Y[0,0] => XOR gate
# Y[0,1] => AND gate

model = keras.models.Sequential([
    keras.layers.Dense(units=4, activation='tanh', input_shape=[2]),# weight = input * units -> 4 * 2
    keras.layers.Dense(units=2, activation='tanh'), # 2 * 4
    keras.layers.Dense(units=2, activation='sigmoid'), # 출력이 0또는 1
])

# units = Neuron의 갯수

opt = keras.optimizers.Adam(learning_rate=0.1)

model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

hist = model.fit(X_train,Y_train, batch_size=4, epochs=1000, shuffle = True, verbose = 0)

print(model.weights)
print("0 xor 0 , 0&0 -> ",model.predict([[0,0]]))
print("0 xor 1 , 0&1 -> ",model.predict([[0,1]]))
print("1 xor 0 , 1&0 -> ",model.predict([[1,0]]))
print("1 xor 1 , 1&1 -> ",model.predict([[1,1]]))

[<tf.Variable 'dense_6/kernel:0' shape=(2, 4) dtype=float32, numpy=
array([[ 2.871724  ,  1.3844593 ,  0.30343193, -3.0804937 ],
       [ 2.9146614 ,  1.2101253 ,  2.6513264 , -0.11650094]],
      dtype=float32)>, <tf.Variable 'dense_6/bias:0' shape=(4,) dtype=float32, numpy=array([-0.31211528, -1.7436028 , -1.3508008 ,  1.3859482 ], dtype=float32)>, <tf.Variable 'dense_7/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 1.0933447,  3.6027727],
       [-2.6521347,  0.5499061],
       [-2.5026567,  1.6257554],
       [ 2.0677445, -1.475912 ]], dtype=float32)>, <tf.Variable 'dense_7/bias:0' shape=(2,) dtype=float32, numpy=array([ 1.4720734 , -0.11989562], dtype=float32)>, <tf.Variable 'dense_8/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 8.09551  , -8.77871  ],
       [ 7.8853493,  1.5147905]], dtype=float32)>, <tf.Variable 'dense_8/bias:0' shape=(2,) dtype=float32, numpy=array([-7.6186543, -1.8553941], dtype=float32)>]
1/1 [==============================] - 0s 64ms/step
0 x